### ISSUE TITLE
not working anymore :( please fix

### ISSUE THREAD

**Issue by sminee** [medenko/Bitefight-Bot-Demo#1]
hello ^_^ 

i think it's an easy fix

it's not working anymore because something pop-up at the start of chrome new windows affects the auto login, i think.

it's a pop-up about gameforge cookies and blah-blah, and a button with "got it"

please solve it asap <3 thankies

**Comment by medenko** [comment]
Updated and uploaded bots, should work now. Thanks for reporting.

**Comment by sminee** [comment]
ty for this fix!

now it has another issue! i reported it too ^_^
