### ISSUE TITLE
after last update

### ISSUE THREAD

**Issue by sminee** [medenko/Bitefight-Bot-Demo#2]
the bot doesn't listen about Story Actions (even if it's about the bot special for aspects)

example:

i set an story actions order, and bot doesn't care about it
i set 5050 destruction, 2550 for chaos or other...and the bot goes automatically for nature & corruption...

thank you for the latest fix, but it's a need to fix this too! this just happened after the last fix, b4 was working

**Comment by medenko** [comment]
Fixed a miscalculation in aspect-related bot, tested it for hours and for me it works as expected. I cannot reproduce issues you have with story order bot though, and therefore no fix available for it.

**Comment by medenko** [comment]
Managed to fix a normal story bot. 
But cannot help with aspects bot and therefore removing it, since it pesist at causing chaos with aspects.
